# Generated by Django 5.0.6 on 2025-10-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_contact_unique_phone_number_created_by'),
        ('app', '0003_enable_trigram'),
    ]

    operations = [
    ]
